In [1]:
#General Imports
import numpy as np

# Task 1
siehe PDF Dokument

In [11]:
l = [1,2,3,4,5]
l[1:3] = ['y','x']
print(l)

[1, 'y', 'x', 4, 5]


In [14]:
l = [1,2,3,4,5]
for i in range(len(l)):
    print (i, l[i])
    
    

0 1
1 2
2 3
3 4
4 5


In [18]:
l = [1,2,3,4,5]
i = 0
for x in l:
    print(i, x)
    i = i+1

0 1
1 2
2 3
3 4
4 5


In [23]:
a = np.array([[1,2,3,4],[1,2,3,4]])
print(a.shape)

(2, 4)


In [29]:
b = np.zeros((2,3))
print(b)
c= np.array((2,3))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
[2 3]


# Task 2

In [32]:
# Zunächst wird das Codewort als Liste l definiert und dann entsprechend der Aufgabenstellung gespalten
l = ['a', 'r', 'b', 'r', 'e', 'e', 'i', 'v', 't', 'd','u','l', 'n', 'i', 'g','b']
a = l[0:2]
b = l[2:]
print(a,b)

['a', 'r'] ['b', 'r', 'e', 'e', 'i', 'v', 't', 'd', 'u', 'l', 'n', 'i', 'g', 'b']


In [39]:
# b wird in b_0 und b_1 aufgeteilt
b_0 = b[::2]
print(b_0)
b_1 = b[1::2]
print(b_1)

['b', 'e', 'i', 't', 'u', 'n', 'g']
['r', 'e', 'v', 'd', 'l', 'i', 'b']


In [40]:
# Die Liste b_1 wird umgedreht
b_1 =b_1[::-1]
print(b_1)

['b', 'i', 'l', 'd', 'v', 'e', 'r']


In [41]:
# Zusammensetzen der Lösung
d= b_1 + a + b_0
print(d)

['b', 'i', 'l', 'd', 'v', 'e', 'r', 'a', 'r', 'b', 'e', 'i', 't', 'u', 'n', 'g']


# Task 3

In [44]:
#Teilaufgabe 1
l= range(100,201)
print(l)



range(100, 201)


In [46]:
#Teilaufgabe 2
def Sum(x):
    y = 0
    for i in x:
        y+=i
    return y
print(Sum(l))


15150


In [47]:
#Teilaufgabe 3
def Mean(x):
    return Sum(x)/len(x)
print(Mean(l))

150.0


In [48]:
# Teilaufgabe 4
def Elements(x):
    ungerade = 0
    gerade = 0
    for i in x:
        if i % 2 == 0:
            gerade +=1
        else:
            ungerade +=1
    return gerade, ungerade
Elements(l)
    

(51, 50)

In [50]:
#Teilaufgabe 5
def isPrime(x):
    for i in range(2,x):
        if x % i == 0:
            return False
    return True

def Prime(x):    
    prims = 0
    for i in l:
        if isPrime(i):
            prims +=1
    return prims
Prime(l)
        

21

# Task 4

In [74]:
# Teilaufgaben 1 bis 3
u = np.zeros(100)
print(u)
v = np.array(range(12))
print(v)
m = v.reshape(3,4)
print(m)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [75]:
# Teilaufgabe 4
m = m*1.2
print(m)

[[ 0.   1.2  2.4  3.6]
 [ 4.8  6.   7.2  8.4]
 [ 9.6 10.8 12.  13.2]]


In [76]:
# Teilaufgabe 5
m = m.astype(int)
print(m)

[[ 0  1  2  3]
 [ 4  6  7  8]
 [ 9 10 12 13]]


In [ ]:
# Teilaufgabe 6 
m = m*1.2
print(m.dtype)

In [80]:
# Teilaufgabe 7
m2 = np.multiply(m,m)
print(m2)

[[  0.     1.44   5.76  12.96]
 [ 23.04  51.84  70.56  92.16]
 [116.64 144.   207.36 243.36]]
